## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [3]:
import pandas as pd

In [31]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [11]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [26]:
# Variant 1
# male_avg_age=data.groupby('sex')['age'].mean()['Male']
# print("Cредний возраст мужчин:", male_avg_age)

# Variant 2
male_avg_age=data[data['sex']=="Male"]["age"].mean()
print("Cредний возраст мужчин:", male_avg_age)

Cредний возраст мужчин: 39.43354749885268

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [13]:
# Variant 1
# len_data=len(data)
# len_us=len(data[data['native-country']=="United-States"])
# share=round(len_us/len_data*100,2)
# print(f"Доля граждан Соединенных Штат: {share}%")

# Variant 2
share=(data["native-country"]=="United-States").mean()
print(f"Доля граждан Соединенных Штат: {share*100}%")

Доля граждан Соединенных Штат: 89.5857006848684%

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [ ]:
data['salary'].value_counts()

high_income=data[data['salary']=='>50K']['age']
low_income=data[data['salary']=='<=50K']['age']

print("Средний возраст (>50K):", high_income.mean())
print("СКО возраста (>50K):", high_income.std())

print("\nСредний возраст (<=50K):", low_income.mean())
print("СКО возраста (<=50K):", low_income.std())

Средний возраст (>50K): 44.24984058155847
СКО возраста (>50K): 10.519027719851826

Средний возраст (<=50K): 36.78373786407767
СКО возраста (<=50K): 14.02008849082488

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [23]:
higher_edu=['Bachelors','Prof-school','Assoc-acdm','Assoc-voc','Masters','Doctorate']
high_salary=data[data['salary']=='>50K']
non_higher=high_salary[~high_salary['education'].isin(higher_edu)]

if len(non_higher)==0:
	print("Да, все люди с доходом выше 50К имеют высшее образование")
else:
	print("Нет, есть люди с доходом >50K без высшего образования. Их количество:", len(non_higher))

Нет, есть люди с доходом >50K без высшего образования. Их количество: 3306

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [ ]:
age_stats=data.groupby(['race','sex'])['age'].describe()
max_age=age_stats.loc[('Asian-Pac-Islander','Male'),'max']
print("Максимальный возраст мужчин Asian-Pac-Islander:", max_age)

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0
Максимальный возраст мужчин Asian-Pac-Islander: 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [ ]:
# Variant 1
# married_status=['Married-civ-spouse','Married-spouse-absent','Married-AF-spouse']
# men=data[data['sex']=='Male'].copy()
# men['is_married']=men['marital-status'].isin(married_status)
# share_high_income=men.groupby('is_married')['salary'].apply(lambda x: (x=='>50K').mean())

# married_share=share_high_income[True]*100
# single_share=share_high_income[False]*100

# print(f"Женатые: {married_share:.2f}%")
# print(f"Холостые: {single_share:.2f}%")

# Variant 2
data['is_married']=data['marital-status'].str.startswith('Married')
data['high_income']=data['salary']=='>50K'
shares=data.groupby('is_married')['high_income'].mean()
if shares[True]>shares[False]:
	print("Среди женатых больше доля зарабатывающих >50K")
else:
	print("Среди холостых больше доля зарабатывающих >50K")

print(shares)

Среди женатых больше доля зарабатывающих >50K
is_married
False    0.064454
True     0.436920
Name: high_income, dtype: float64

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [60]:
max_hours=data['hours-per-week'].max()
print("Максимальное число часов в неделю:", max_hours)
max_hours_workers=data[data['hours-per-week'] == max_hours]
num_max_hours=len(max_hours_workers)
print("Количество людей, работающих максимум часов:", num_max_hours)
count_hard_workers=max_hours_workers.groupby('salary')['salary'].count()
share_high_income=count_hard_workers.get(">50K",0)/num_max_hours*100
print(f'Процент зарабатывающих много: {share_high_income:.2f}%')

Максимальное число часов в неделю: 99
Количество людей, работающих максимум часов: 85
Процент зарабатывающих много: 29.41%

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [170]:
data['hours-per-week'].mean()
avg_hours=data.groupby(['native-country', 'salary'])['hours-per-week'].mean().reset_index(name='avg_hours')
print("Cреднее время работы зарабатывающих мало и много для каждой страны:\n", avg_hours)

Cреднее время работы зарабатывающих мало и много для каждой страны:
    native-country salary  avg_hours
0               ?  <=50K  40.164760
1               ?   >50K  45.547945
2        Cambodia  <=50K  41.416667
3        Cambodia   >50K  40.000000
4          Canada  <=50K  37.914634
..            ...    ...        ...
77  United-States   >50K  45.505369
78        Vietnam  <=50K  37.193548
79        Vietnam   >50K  39.200000
80     Yugoslavia  <=50K  41.600000
81     Yugoslavia   >50K  49.500000

[82 rows x 3 columns]

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [ ]:
bins=[16, 35, 70, 100]
labels=['young','adult','retiree']
data['AgeGroup']=pd.cut(data['age'],bins=bins,labels=labels,right=False)
data[['age','AgeGroup']]

       age AgeGroup
0       39    adult
1       50    adult
2       38    adult
3       53    adult
4       28    young
...    ...      ...
32556   27    young
32557   40    adult
32558   58    adult
32559   22    young
32560   52    adult

[32561 rows x 2 columns]

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [189]:
num_high_income_group=data[data['salary']=='>50K'].groupby('AgeGroup',observed=True).size()
print(num_high_income_group)
print('Возрастная группа, в которой чаще зарабатывают больше 50К:', num_high_income_group.idxmax())

AgeGroup
young      1488
adult      6240
retiree     113
dtype: int64
Возрастная группа, в которой чаще зарабатывают больше 50К: adult

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функцию фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [ ]:
# Variant 1
# print('Количество людей в каждой группе:\n', data.groupby('occupation').size().reset_index(name="num_people"))

# def filter_func(group):
# 	return (group['age'].mean()<=40) and (group['hours-per-week'].min()>5)

# filtered=data.groupby('occupation').filter(filter_func)
# counts_filtered = filtered.groupby('occupation').size().reset_index(name="num_people")
# print('\nФильтрация групп:\n', counts_filtered)

# Variant 2
data_clean=data[data['occupation']!="?"]
counts_before = data_clean.groupby('occupation').size().reset_index(name="num_people")

# агрегаты для каждой професии
agg = data_clean.groupby('occupation').agg(
    avg_age=('age', 'mean'),
    min_hours=('hours-per-week', 'min'),
    num_people=('age', 'size')
).reset_index()
agg

def filter_func(group_agg):
    return (group_agg['avg_age'] <= 40) & (group_agg['min_hours'] > 5)

mask = filter_func(agg)
agg_filtered = agg[mask]

# профессии, которые прошли фильтр
passed_occupations = agg_filtered['occupation']
counts_before['passed_filter'] = counts_before['occupation'].isin(passed_occupations)

print("\nСравнение количества людей по профессиям и фильтру:\n", counts_before)

Сравнение количества людей по профессиям и фильтру (проще):
            occupation  num_people  passed_filter
0        Adm-clerical        3770          False
1        Armed-Forces           9           True
2        Craft-repair        4099          False
3     Exec-managerial        4066          False
4     Farming-fishing         994          False
5   Handlers-cleaners        1370          False
6   Machine-op-inspct        2002          False
7       Other-service        3295          False
8     Priv-house-serv         149          False
9      Prof-specialty        4140          False
10    Protective-serv         649          False
11              Sales        3650          False
12       Tech-support         928          False
13   Transport-moving        1597          False